imports:
    - { resource: '../config.yml' }
    - { resource: 'security.yml' }
    - { resource: 'services.yml' }

framework:
    router:
        resource: '%kernel.root_dir%/config/admin/routing.yml'
        strict_requirements: ~

