parameters:
    database_driver:         "pdo_mysql"
    #database_server_version: "5.6.23"
    debug_toolbar:           true
    debug_redirects:         false
    locale:                  "en"
    mailer_transport:        "gmail"
    mailer_host:             "smtp.gmail.com"
