imports:
    - { resource: ../config.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/api/routing.yml"
        strict_requirements: ~

